# Generated by Django 5.1.5 on 2025-02-12 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mdb', '0003_add_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_base', models.GenericIPAddressField(protocol='IPv4', verbose_name='ipv4 base')),
                ('submask', models.GenericIPAddressField(protocol='IPv4', verbose_name='submask')),
                ('name', models.TextField(default='<ip_set>', verbose_name='ip_set name')),
            ],
        ),
        migrations.CreateModel(
            name='MachineIpEntry',
            fields=[
                ('ip', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='ip')),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='mdb.machine')),
                ('ip_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dhcp.ipset')),
            ],
        ),
    ]
