# Generated by Django 5.1.5 on 2025-02-13 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0001_initial'),
        ('mdb', '0003_add_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipset',
            name='ipv4_base',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='ipv4 base'),
        ),
        migrations.CreateModel(
            name='RoomIpSetBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dhcp.ipset')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mdb.room', unique=True)),
            ],
        ),
    ]
