# Generated by Django 5.1.5 on 2025-02-13 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0002_alter_ipset_ipv4_base_roomipsetbinding'),
        ('mdb', '0003_add_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomipsetbinding',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='mdb.room'),
        ),
    ]
