# Generated by Django 5.1.5 on 2025-02-13 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhcp', '0003_alter_roomipsetbinding_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', unique=True, verbose_name='ip')),
            ],
        ),
        migrations.AlterField(
            model_name='machineipentry',
            name='ip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dhcp.ip'),
        ),
    ]
