# Generated by Django 5.0.7 on 2025-01-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0001_add_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name="Group Name")),
            ],
        ),
    ]
