# Generated by Django 5.0.7 on 2025-01-27 23:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0002_add_mgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32, unique=True, verbose_name='Host name')),
                ('mac', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator('[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}')], verbose_name='MAC Address')),
                ('secret', models.CharField(max_length=64, null=True, validators=[django.core.validators.RegexValidator('[0-9a-fA-F]{64}')], verbose_name='Secret')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mdb.machinegroup', verbose_name='Group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mdb.room', verbose_name='Room')),
            ],
        ),
    ]
