# Generated by Django 5.1.5 on 2025-02-03 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0003_add_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='last_ping',
            field=models.DateTimeField(default=None, verbose_name='Last ping'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='host',
            field=models.CharField(max_length=32, unique=True, verbose_name='Host Name'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mac',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Enter valid MAC Address', regex='[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}')], verbose_name='MAC Address'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='secret',
            field=models.CharField(max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Invalid Secret', regex='[0-9a-fA-F]{64}')], verbose_name='Secret'),
        ),
    ]
