# Generated by Django 5.1.5 on 2025-02-03 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdb', '0004_machine_last_ping_alter_machine_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='last_ping',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 9, 30, 48, 339158), verbose_name='Last ping'),
        ),
    ]
